#! /usr/bin/env php
<?php
// The library works fine as an executable as well
// This example is Unix-ish specific
// Usage
// ./basic test

require dirname(__DIR__) . '/vendor/autoload.php';

$cmd = new Commando\Command();

echo "Argument #1: " . $cmd[0] . PHP_EOL;